export const queryKeys = {
      subjects: ["subjects"] as const,
      classes: ["classes"] as const,
      users: (search?: string, role?: string, page?: number) => ["users", { search, role, page }] as const,
      enrollments: (classId?: string) => ["enrollments", { classId }] as const,
      teacherAssignments: (teacherId?: string) => ["teacher-assignments", { teacherId }] as const,
      assignments: ["assignments"] as const,
      assignment: (id: string) => ["assignments", id] as const,
      submissions: (assignmentId: string) => ["submissions", { assignmentId }] as const,
      mySubmissions: ["submissions", "mine"] as const,
      dashboard: ["dashboard"] as const,
      settings: ["settings"] as const,
      notifications: ["notifications"] as const,
      notificationsUnread: ["notifications", "unread-count"] as const,
};
